"""added tts type for calls

Revision ID: 2029c42f3d94
Revises: 35a848718a6e
Create Date: 2025-08-30 11:53:34.318007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2029c42f3d94"
down_revision: Union[str, None] = "35a848718a6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calls",
        sa.Column("tts_type", sa.String(), nullable=False, server_default="ssugt"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calls", "tts_type")
    # ### end Alembic commands ###

