"""added categories for calls

Revision ID: c0ab47b94a52
Revises: 2029c42f3d94
Create Date: 2025-09-05 15:44:36.938518

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
DEFAULT_CATEGORIES = ["ru_mobile_numbers", "ru_city_numbers", "international_numbers"]
revision: str = "c0ab47b94a52"
down_revision: Union[str, None] = "2029c42f3d94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    default_categories = "{" + ",".join([f'"{c}"' for c in DEFAULT_CATEGORIES]) + "}"

    op.add_column(
        "calls",
        sa.Column(
            "categories",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text(f"'{default_categories}'::text[]"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calls", "categories")
    # ### end Alembic commands ###

