"""set default schedule for calls

Revision ID: 35a848718a6e
Revises: f95efa539594
Create Date: 2025-08-11 11:08:57.004871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

DEFAULT_SCHEDULE = """
[{"weekday":"monday","time_ranges":[{"start_time_at":"09:00","end_time_at":"17:00","max_num_channels_occupied":2},{"start_time_at":"00:00","end_time_at":"09:00","max_num_channels_occupied":5},{"start_time_at":"17:00","end_time_at":"23:59","max_num_channels_occupied":5}]},{"weekday":"tuesday","time_ranges":[{"start_time_at":"09:00","end_time_at":"17:00","max_num_channels_occupied":2},{"start_time_at":"00:00","end_time_at":"09:00","max_num_channels_occupied":5},{"start_time_at":"17:00","end_time_at":"23:59","max_num_channels_occupied":5}]},{"weekday":"wednesday","time_ranges":[{"start_time_at":"09:00","end_time_at":"17:00","max_num_channels_occupied":2},{"start_time_at":"00:00","end_time_at":"09:00","max_num_channels_occupied":5},{"start_time_at":"17:00","end_time_at":"23:59","max_num_channels_occupied":5}]},{"weekday":"thursday","time_ranges":[{"start_time_at":"09:00","end_time_at":"17:00","max_num_channels_occupied":2},{"start_time_at":"00:00","end_time_at":"09:00","max_num_channels_occupied":5},{"start_time_at":"17:00","end_time_at":"23:59","max_num_channels_occupied":5}]},{"weekday":"friday","time_ranges":[{"start_time_at":"09:00","end_time_at":"17:00","max_num_channels_occupied":2},{"start_time_at":"00:00","end_time_at":"09:00","max_num_channels_occupied":5},{"start_time_at":"17:00","end_time_at":"23:59","max_num_channels_occupied":5}]},{"weekday":"saturday","time_ranges":[{"start_time_at":"00:00","end_time_at":"23:59","max_num_channels_occupied":5}]},{"weekday":"sunday","time_ranges":[{"start_time_at":"00:00","end_time_at":"23:59","max_num_channels_occupied":5}]}]
"""
revision: str = "35a848718a6e"
down_revision: Union[str, None] = "f95efa539594"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE calls SET schedule = :schedule WHERE schedule IS NULL"),
        {"schedule": DEFAULT_SCHEDULE},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

