"""added retry limit and count for calls

Revision ID: f040f4373cde
Revises: 6790aba27baa
Create Date: 2025-06-29 14:02:51.256501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text, null

# revision identifiers, used by Alembic.
revision: str = "f040f4373cde"
down_revision: Union[str, None] = "6790aba27baa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calls",
        sa.Column(
            "retry_limit", sa.Integer(), nullable=False, server_default=text("0")
        ),
    )
    op.add_column(
        "phone_calls",
        sa.Column("next_retry_at", sa.DateTime(), nullable=True, server_default=null()),
    )
    op.add_column(
        "phone_calls",
        sa.Column(
            "retry_count", sa.Integer(), nullable=False, server_default=text("0")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phone_calls", "retry_count")
    op.drop_column("phone_calls", "next_retry_at")
    op.drop_column("calls", "retry_limit")
    # ### end Alembic commands ###

