"""added calls and phone calls

Revision ID: e0eb0a9959e5
Revises: 
Create Date: 2025-06-08 10:14:44.906222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0eb0a9959e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls'))
    )
    op.create_table('phone_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('synthesis', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('ringing_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('cause', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_phone_calls_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_calls'))
    )
    op.create_index(op.f('ix_phone_calls_channel_id'), 'phone_calls', ['channel_id'], unique=True)
    op.create_index(op.f('ix_phone_calls_phone_number'), 'phone_calls', ['phone_number'], unique=False)
    op.create_index('unique_ringing_call_per_number', 'phone_calls', ['phone_number'], unique=True, postgresql_where=sa.text("status = 'ringing'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_ringing_call_per_number', table_name='phone_calls', postgresql_where=sa.text("status = 'ringing'"))
    op.drop_index(op.f('ix_phone_calls_phone_number'), table_name='phone_calls')
    op.drop_index(op.f('ix_phone_calls_channel_id'), table_name='phone_calls')
    op.drop_table('phone_calls')
    op.drop_table('calls')
    # ### end Alembic commands ###

