"""added schedule for calls

Revision ID: f95efa539594
Revises: f040f4373cde
Create Date: 2025-07-13 06:25:19.452858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import null
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f95efa539594"
down_revision: Union[str, None] = "f040f4373cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calls",
        sa.Column(
            "schedule",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            server_default=null(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calls", "schedule")
    # ### end Alembic commands ###

