"""added is paused for calls

Revision ID: 6790aba27baa
Revises: e0eb0a9959e5
Create Date: 2025-06-17 14:10:57.299228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import false

# revision identifiers, used by Alembic.
revision: str = "6790aba27baa"
down_revision: Union[str, None] = "e0eb0a9959e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calls",
        sa.Column("is_paused", sa.Boolean(), nullable=False, server_default=false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calls", "is_paused")
    # ### end Alembic commands ###

