"""add_email_to_user

Revision ID: 6052a723cbca
Revises: f5b7e0aece71
Create Date: 2026-03-10 09:17:26.831866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6052a723cbca'
down_revision: Union[str, None] = 'f5b7e0aece71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'email')
    op.alter_column('calls', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###

