"""add_report_fields

Revision ID: 4fb3d988cbbc
Revises: fd1caa3a30e4
Create Date: 2026-06-20 10:22:56.165062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb3d988cbbc'
down_revision: Union[str, None] = 'fd1caa3a30e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('control_call_number', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('control_call_interval', sa.Integer(), server_default='0', nullable=False))
    op.add_column('calls', sa.Column('control_call_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('calls', sa.Column('current_control_call_counter', sa.Integer(), server_default='0', nullable=False))
    op.add_column('calls', sa.Column('email_report_address', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('email_report_interval', sa.Integer(), server_default='0', nullable=False))
    op.add_column('calls', sa.Column('email_report_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('calls', sa.Column('current_email_report_counter', sa.Integer(), server_default='0', nullable=False))
    op.add_column('calls', sa.Column('email_report_trigger_start', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('calls', sa.Column('email_report_trigger_interval', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('calls', sa.Column('email_report_trigger_final', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'email_report_trigger_final')
    op.drop_column('calls', 'email_report_trigger_interval')
    op.drop_column('calls', 'email_report_trigger_start')
    op.drop_column('calls', 'current_email_report_counter')
    op.drop_column('calls', 'email_report_enabled')
    op.drop_column('calls', 'email_report_interval')
    op.drop_column('calls', 'email_report_address')
    op.drop_column('calls', 'current_control_call_counter')
    op.drop_column('calls', 'control_call_enabled')
    op.drop_column('calls', 'control_call_interval')
    op.drop_column('calls', 'control_call_number')
    # ### end Alembic commands ###

